In [5]:
import pandas as pd
import numpy as np

small_counts = np.random.randint(0, 100, 20)
print(small_counts)

print(np.floor_divide(small_counts, 10))
large_counts = [296, 8286, 64011, 80, 3, 725, 867, 2215, 7689, 11495, 91897, 44, 28, 7971,
926, 12]

print(pd.qcut(large_counts, 4, labels=False))

large_counts_series = pd.Series(large_counts)

print(large_counts_series.quantile([0.25, 0.5, 0.75]))

[18 43 65 40 18  2 13 73 45 60 43 33  2 10 97 55 22 52 40 43]
[1 4 6 4 1 0 1 7 4 6 4 3 0 1 9 5 2 5 4 4]
[1 3 3 1 0 1 1 2 2 3 3 0 0 2 2 0]
0.25      71.00
0.50     896.50
0.75    8049.75
dtype: float64
